import React from 'react';
import GlassCard from '../components/GlassCard';
import { FaInfoCircle, FaHeartbeat, FaCode } from 'react-icons/fa';

const About = () => {
  return (
    <div className="space-y-6">
      
      {/* Title */}
      <div>
        <h2 className="text-2xl font-extrabold font-sans">About DiaPredict AI</h2>
        <p className="text-xs text-slate-400 dark:text-slate-500">
          Learn about our mission, tech stack integration, and medical disclaimers.
        </p>
      </div>

      <div className="max-w-3xl mx-auto space-y-6 text-left">
        
        {/* Core Info */}
        <GlassCard>
          <h3 className="font-bold text-sm mb-4 flex items-center space-x-2 text-primary-500">
            <FaInfoCircle />
            <span>Our Mission & Core Vision</span>
          </h3>
          <div className="space-y-3 text-xs leading-relaxed text-slate-500 dark:text-slate-400">
            <p>
              DiaPredict AI was conceptualized to help users manage diabetes systematically through technology. By tracking daily parameters (blood glucose, water volumes, physical exercises) and matching them with a rule-based AI engine, our goal is to deliver easy, readable clinical trends to users.
            </p>
            <p>
              Through early warnings, calorie targets adjustments, and nutritional templates rotation, we aim to prevent critical hyperglycemia levels and help users coordinate their wellness roadmap.
            </p>
          </div>
        </GlassCard>

        {/* Tech Stack */}
        <GlassCard>
          <h3 className="font-bold text-sm mb-4 flex items-center space-x-2 text-primary-500">
            <FaCode />
            <span>System Tech Integration Stack</span>
          </h3>
          <div className="space-y-2 text-xs text-slate-500 dark:text-slate-400">
            <p>DiaPredict AI is engineered using modern full-stack web technologies:</p>
            <ul className="list-disc list-inside pl-2 space-y-1">
              <li><strong>Frontend:</strong> React (Vite template) + Tailwind CSS + Framer Motion.</li>
              <li><strong>Charts:</strong> Responsive Chart.js integrated via react-chartjs-2.</li>
              <li><strong>Backend:</strong> Node.js + Express.js API service server.</li>
              <li><strong>Storage:</strong> Firebase Firestore (with local database fallback compatibility).</li>
              <li><strong>Verification:</strong> Custom JWT token authorizations.</li>
            </ul>
          </div>
        </GlassCard>

        {/* Health Disclaimer */}
        <GlassCard className="border-l-4 border-amber-500 bg-amber-500/5 text-amber-600 dark:text-amber-400">
          <h3 className="font-bold text-sm mb-3 flex items-center space-x-2">
            <FaHeartbeat className="animate-pulse" />
            <span>CRITICAL CLINICAL HEALTH DISCLAIMER</span>
          </h3>
          <p className="text-xs leading-relaxed">
            DiaPredict AI is designed as a tracking tool for lifestyle and general monitoring. All suggestions, target calorie ratios, classification categories (Normal, Prediabetic, High Risk), and diet tips generated by the AI Engine do NOT constitute formal medical diagnosis, prescriptions, or clinical treatments. Always coordinate with your physician, doctor, or certified endocrinologist before starting new diets or heavy workout routines.
          </p>
        </GlassCard>

      </div>

    </div>
  );
};

export default About;
